/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package psd1.form;

import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import javax.swing.JOptionPane;
import psd1.controller.Controller;
import psd1.domain.Nastavnik;
import psd1.domain.Zvanje;
import java.sql.*;
import java.util.List;

/**
 *
 * @author pc
 */
public class DialogNastavnik extends javax.swing.JDialog {

    Nastavnik n;
    int view;
    boolean update = false;

    /**
     * Creates new form DialogNastavnik
     */
    public DialogNastavnik(java.awt.Frame parent, boolean modal, Nastavnik nastavnik, int view) {
        initComponents();
        this.n = nastavnik;
        this.view = view;
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPrezime = new javax.swing.JLabel();
        labelZvanje = new javax.swing.JLabel();
        textInputIme = new javax.swing.JTextField();
        textInputPrezime = new javax.swing.JTextField();
        cbZvanje = new javax.swing.JComboBox();
        btnAdd = new javax.swing.JButton();
        btnChange = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        labelIme = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelPrezime.setText("prezime");

        labelZvanje.setText("zvanje");

        cbZvanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbZvanjeActionPerformed(evt);
            }
        });

        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnChange.setText("IZMENI");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        btnDelete.setText("OBRISI");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        labelIme.setText("ime");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelIme, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textInputIme))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textInputPrezime))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelZvanje, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addGap(18, 18, 18)
                                .addComponent(btnChange)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDelete)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cbZvanje, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIme)
                    .addComponent(textInputIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textInputPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPrezime))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelZvanje)
                    .addComponent(cbZvanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnChange)
                    .addComponent(btnDelete))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbZvanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbZvanjeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbZvanjeActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String ime = textInputIme.getText();
        String prezime = textInputPrezime.getText();
        Zvanje zvanje = (Zvanje) cbZvanje.getSelectedItem();
        try {

            if (update == false) {

                 n = new Nastavnik(ime, prezime, zvanje);
                if (n.isValid()) {
                    Controller.getInstance().insertUpdate(n, update);
                } else {
                    JOptionPane.showMessageDialog(this, "Nevalidni unos", "Greska", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                 n= new Nastavnik(n.getId(), ime, prezime, zvanje);
                if(n.isValid()){
                    Controller.getInstance().insertUpdate(n, update);
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        this.dispose();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        int a = JOptionPane.showConfirmDialog(null, "Da li zelite da obriste nastavnika", "Delete", JOptionPane.YES_NO_OPTION);
        if (a == JOptionPane.YES_OPTION) {
            try {
                Controller.getInstance().removeNastavnik(n.getId());
                System.out.println("Usespno obrisan nastavnik sa id" + n.getId());
                this.dispose();
            } catch (SQLException ex) {
                this.dispose();
                ex.printStackTrace();
            }
        } else {

        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
       
            update();
            
    }//GEN-LAST:event_btnChangeActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DialogNastavnik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DialogNastavnik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DialogNastavnik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DialogNastavnik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DialogNastavnik dialog = new DialogNastavnik(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnDelete;
    private javax.swing.JComboBox cbZvanje;
    private javax.swing.JLabel labelIme;
    private javax.swing.JLabel labelPrezime;
    private javax.swing.JLabel labelZvanje;
    private javax.swing.JTextField textInputIme;
    private javax.swing.JTextField textInputPrezime;
    // End of variables declaration//GEN-END:variables
private void prepareView() {

        List<Zvanje> zvanja = Controller.getInstance().getAllZvanja();
        for (Zvanje zvanje : zvanja) {
            cbZvanje.addItem(zvanje);
        }

        switch (view) {
            case 1:
                prepareAdd();
                break;
            case 2://update
                update();
                break;
            case 3:
                view();
                break;//view
        }

    }

    private void view() {
        textInputIme.setEditable(false);
        textInputPrezime.setEditable(false);
        cbZvanje.setEnabled(false);
        btnAdd.setVisible(false);
        btnChange.setVisible(true);

        textInputIme.setText(n.getIme());
        textInputPrezime.setText(n.getPrezime());
        cbZvanje.setSelectedItem(n.getZvanje());
    }

    private void prepareAdd() {
        btnDelete.setVisible(false);
        btnChange.setVisible(false);
    }

    private void update() {
        textInputIme.setEditable(true);
        textInputPrezime.setEditable(true);
        cbZvanje.setEnabled(true);
        btnAdd.setVisible(true);
        btnChange.setVisible(false);
        btnDelete.setVisible(false);

        textInputIme.setText(n.getIme());
        textInputPrezime.setText(n.getPrezime());
      //  cbZvanje.setSelectedItem(n.getZvanje());
        update=!update;
    }

}
